fix: get branch name in delete workflow properly

diff --git a/.github/workflows/development-release-delete.yml b/.github/workflows/development-release-delete.yml
--- a/.github/workflows/development-release-delete.yml
+++ b/.github/workflows/development-release-delete.yml
@@ -17,15 +17,16 @@ jobs:
       - name: Checkout main
         uses: actions/checkout@v4
 
-      - uses: mdecoleman/pr-branch-name@2.0.0
-        id: vars
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Extract branch name
-        shell: bash
-        run: echo "name=$(echo ${{ steps.vars.outputs.branch }} | sed 's/^dev\///')" >> $GITHUB_ENV
         id: extract_branch
+        shell: bash
+        run: |
+          branch=${{ github.event.pull_request.head.ref || github.event.ref }}
+          if [[ -z "$branch" ]]; then
+              echo "Error: neither github.event.pull_request.head.ref nor github.event.ref exist."
+              exit 1
+          fi
+          echo "BRANCH_NAME=$(echo $branch | sed 's/^dev\///')" >> $GITHUB_ENV
 
       - name: Install doctl
         uses: digitalocean/action-doctl@v2
@@ -38,8 +39,8 @@ jobs:
       - name: Remove pre-release artifacts
         continue-on-error: true
         run: |
-          NAME=${{ env.name }} && sed -i 's|<BRANCH>|'${NAME}'|' $GITHUB_WORKSPACE/deployment/development/all.yaml
-          NAME=${{ env.name }} && sed -i 's|<BRANCH>|'${NAME}'|' $GITHUB_WORKSPACE/deployment/development/deployment.yaml
+          NAME=${{ env.BRANCH_NAME }} && sed -i 's|<BRANCH>|'${NAME}'|' $GITHUB_WORKSPACE/deployment/development/all.yaml
+          NAME=${{ env.BRANCH_NAME }} && sed -i 's|<BRANCH>|'${NAME}'|' $GITHUB_WORKSPACE/deployment/development/deployment.yaml
           kubectl delete -f $GITHUB_WORKSPACE/deployment/development/
 
       - name: Get Cloudflare record ID
@@ -48,7 +49,7 @@ jobs:
         shell: bash
         run: |
           LOADBALANCER_IP=$(kubectl get svc -n nginx nginx-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-          echo "record=$(echo $(curl -X GET "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/dns_records?type=A&name=dev-${{ env.name }}-epicapp.subsocial.network&content=$LOADBALANCER_IP&proxied=true&page=1&per_page=100&order=type&direction=desc&match=all"  -H "X-Auth-Email:${{ secrets.CF_MAIL }}"      -H "Authorization:Bearer ${{ secrets.CF_TOKEN }}"      -H "Content-Type:application/json" |  jq . | jq -c '.result[]' | jq -r .id) )" >> $GITHUB_ENV
+          echo "record=$(echo $(curl -X GET "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/dns_records?type=A&name=dev-${{ env.BRANCH_NAME }}-epicapp.subsocial.network&content=$LOADBALANCER_IP&proxied=true&page=1&per_page=100&order=type&direction=desc&match=all"  -H "X-Auth-Email:${{ secrets.CF_MAIL }}"      -H "Authorization:Bearer ${{ secrets.CF_TOKEN }}"      -H "Content-Type:application/json" |  jq . | jq -c '.result[]' | jq -r .id) )" >> $GITHUB_ENV
 
       - name: Delete Cloudflare record
         continue-on-error: true
